/**
 * Install command – register HAEVN as a Chrome native messaging host.
 *
 * Chrome spawns native hosts by executing the binary at `path` in the manifest
 * with no special flags.  To tell the CLI it is running as a native host we
 * generate a tiny wrapper shell script that appends --native-host, then point
 * the manifest at that wrapper instead of the CLI binary directly.
 *
 *   ~/.haevn/native-host.sh  ← manifest path
 *      └─ exec /abs/path/to/haevn --native-host "$@"
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { defineCommand } from "citty";
import { generateManifest } from "./protocol";
import { consola } from "../utils/output";

/** Directory used for all HAEVN user data (socket, wrapper, etc.) */
const HAEVN_DIR = path.join(os.homedir(), ".haevn");

/** Path to the generated wrapper script. */
const WRAPPER_PATH = path.join(HAEVN_DIR, "native-host.sh");

export default defineCommand({
  meta: {
    name: "install",
    description: "Install native messaging host for Chrome/Chromium integration",
  },
  args: {
    extensionId: {
      type: "string",
      alias: "e",
      description: "Chrome extension ID (required)",
      required: true,
    },
    browser: {
      type: "string",
      alias: "b",
      description: "Browser to install for: chrome (default), chromium, edge",
      default: "chrome",
    },
  },
  async run({ args }) {
    const { extensionId, browser } = args;

    // ── 1. Resolve the absolute path to this CLI binary ──────────────────────
    const cliPath = process.argv[1];
    if (!cliPath) {
      consola.error("Could not determine CLI binary path (process.argv[1] is empty).");
      process.exit(1);
    }
    const absCliPath = path.resolve(cliPath);

    consola.info(`Installing native messaging host for ${browser}…`);
    consola.info(`CLI binary : ${absCliPath}`);
    consola.info(`Extension  : ${extensionId}`);

    // ── 2. Write the wrapper shell script ────────────────────────────────────
    // Chrome executes the binary at `path` in the manifest with no extra flags.
    // The wrapper adds --native-host so the CLI knows it was spawned by Chrome.
    fs.mkdirSync(HAEVN_DIR, { recursive: true });

    const wrapperContent = [
      "#!/bin/sh",
      "# HAEVN Native Messaging Host wrapper",
      "# Generated by `haevn install`. Do not edit manually.",
      `exec ${JSON.stringify(absCliPath)} --native-host "$@"`,
    ].join("\n") + "\n";

    fs.writeFileSync(WRAPPER_PATH, wrapperContent, { mode: 0o755 });
    consola.success(`Wrapper script : ${WRAPPER_PATH}`);

    // ── 3. Write the native messaging manifest ───────────────────────────────
    // The manifest `path` points to the wrapper, not the CLI binary directly.
    const manifest = generateManifest(WRAPPER_PATH, extensionId);
    const manifestPath = getManifestPath(browser);

    fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    consola.success(`NM manifest    : ${manifestPath}`);

    // ── 4. Next steps ─────────────────────────────────────────────────────────
    consola.box(
      [
        "Native messaging host installed!\n",
        "Next step: reload the HAEVN extension in Chrome.",
        "  • chrome://extensions → HAEVN → ⟳ reload",
        "  • Or: haevnDebug.reload() from the Options console\n",
        "Then verify the daemon started:",
        `  ls -la ${path.join(HAEVN_DIR, "daemon.sock")}\n`,
        "Test a command:",
        "  haevn list",
      ].join("\n"),
    );
  },
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getManifestPath(browser: string): string {
  const home = os.homedir();

  switch (process.platform) {
    case "darwin":
      return path.join(
        home,
        "Library",
        "Application Support",
        getBrowserConfigDir(browser),
        "NativeMessagingHosts",
        "com.haevn.cli.json",
      );
    case "linux":
      return path.join(
        home,
        ".config",
        getBrowserConfigDir(browser),
        "NativeMessagingHosts",
        "com.haevn.cli.json",
      );
    case "win32":
      // Windows requires a registry entry; the manifest file path is registered
      // separately.  Throw for now – add registry support when needed.
      throw new Error(
        "Windows installation is not yet supported automatically.\n" +
          "See: https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging#windows",
      );
    default:
      throw new Error(`Unsupported platform: ${process.platform}`);
  }
}

function getBrowserConfigDir(browser: string): string {
  switch (browser) {
    case "chrome":
      return "Google/Chrome";
    case "chromium":
      return "Chromium";
    case "edge":
      return "Microsoft Edge";
    default:
      return browser;
  }
}
