// Gallery/Thumbnail message handlers

import type { BackgroundRequest, BackgroundResponse } from "../../types/messaging";
import type { MediaRoleFilter, MediaTypeFilter } from "../../types/workerMessages";
import { log } from "../../utils/logger";
import { sendWorkerRequest } from "../../utils/workerApi";

/**
 * Handle request to get gallery media with filters and pagination
 */
export async function handleGetGalleryMedia(
  message: Extract<BackgroundRequest, { action: "getGalleryMedia" }>,
  sendResponse: (response: BackgroundResponse) => void,
): Promise<void> {
  try {
    const { offset, limit, filterProvider, filterRole, filterMediaType, sortBy, sortDirection } =
      message;

    // Use unified worker API
    const result = await sendWorkerRequest("thumbnail", {
      type: "getThumbnails",
      requestId: "", // Will be generated by sendWorkerRequest
      offset,
      limit,
      filterProvider,
      filterRole: filterRole as MediaRoleFilter | undefined,
      filterMediaType: filterMediaType as MediaTypeFilter | undefined,
      sortBy,
      sortDirection,
    });

    if (!result || result.type !== "thumbnailsResult") {
      throw new Error("Invalid response from thumbnail worker");
    }

    // Send successful response
    sendResponse({
      success: true,
      items: result.items,
      total: result.total,
    });
  } catch (error) {
    log.error("[GalleryHandlers] Error getting gallery media:", error);
    sendResponse({
      success: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

/**
 * Handle request to generate thumbnails for a specific chat (fire-and-forget)
 * This is called after sync operations to automatically generate thumbnails
 */
export async function handleGenerateThumbnails(chatId: string): Promise<void> {
  try {
    log.info(`[GalleryHandlers] Generating thumbnails for chat ${chatId}`);

    // Use unified worker API with fire-and-forget mode
    await sendWorkerRequest(
      "thumbnail",
      {
        type: "generateForChat",
        chatId,
      },
      { expectResponse: false },
    );
  } catch (error) {
    log.error(`[GalleryHandlers] Error initiating thumbnail generation for chat ${chatId}:`, error);
    // Don't throw - this is fire-and-forget
  }
}

/**
 * Handle request to get full-resolution content for a specific media item (lazy loading)
 */
export async function handleGetGalleryContent(
  message: Extract<BackgroundRequest, { action: "getGalleryContent" }>,
  sendResponse: (response: BackgroundResponse) => void,
): Promise<void> {
  try {
    const result = await sendWorkerRequest("thumbnail", {
      type: "getMediaContent",
      requestId: "", // Will be generated by sendWorkerRequest
      chatId: message.chatId,
      messageId: message.messageId,
    });

    if (!result || result.type !== "mediaContentResult") {
      throw new Error("Invalid response from thumbnail worker");
    }

    sendResponse({ success: true, data: result.content });
  } catch (error) {
    sendResponse({
      success: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

/**
 * Check for missing thumbnails and initiate batch generation (startup routine or manual request)
 */
export async function handleCheckMissingThumbnails(
  _message: Extract<BackgroundRequest, { action: "checkMissingThumbnails" }> | undefined,
  sendResponse?: (response: BackgroundResponse) => void,
): Promise<void> {
  try {
    log.info("[GalleryHandlers] Checking for missing thumbnails...");

    // Use unified worker API to check for missing thumbnails
    const result = await sendWorkerRequest("thumbnail", {
      type: "checkMissing",
      requestId: "", // Will be generated by sendWorkerRequest
    });

    if (!result || result.type !== "missingCount") {
      log.error("[GalleryHandlers] Invalid response from thumbnail worker");
      sendResponse?.({ success: false, error: "Invalid response from thumbnail worker" });
      return;
    }

    if (result.count === 0) {
      log.info("[GalleryHandlers] No missing thumbnails found");
      sendResponse?.({ success: true, count: 0 });
      return;
    }

    log.info(`[GalleryHandlers] Found ${result.count} chats missing thumbnails, generating...`);

    // Initiate batch generation (fire-and-forget)
    await sendWorkerRequest(
      "thumbnail",
      {
        type: "generateBatch",
        chatIds: result.chatIds,
        batchSize: 10,
      },
      { expectResponse: false },
    );

    sendResponse?.({ success: true, count: result.count });
  } catch (error) {
    log.error("[GalleryHandlers] Error checking for missing thumbnails:", error);
    sendResponse?.({
      success: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}
